Repository Hacktoberfest-2021/2022_problem, pull requests merged in 2022-10, with the labels that each got.

#2 solved the issue #1
  bin.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#4 Linear search solved #3
  linear.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#6 solved the parenthesis matching #5
  paranthesis.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#8 Create infix_to_postfix.cpp #7
  infix_to_postfix.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#9 Fibonacci Series Program
  fibonacci.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#15 Solved the issue of swapping #11
  swap.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#16 Issue solved Vowel count #12
  VowelCount
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#17 issue solved Palindrome #13
  Palindrome.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#18 issue solved #14
  anagram.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#23 Issue resolved
  Swap.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#24 Issue rersolved#12
  vowel.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#25 Issue resolved #13
  PalindromeChange.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#26 Issue Resolved#14
  anagramChange.cpp
Labels: hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#32 Issue solved successfully #11
  StringReverseOfficial.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#35 Issue resolved #31
  PermutationCheckOfficial.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022

#33 Issue resolved Vowel check #12
  vowelCheckOfficial.cpp
Labels: good first issue, hacktoberfest, hacktoberfest-accepted, hacktoberfest2022
